name: Test (scratch)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  check_duplicate:
    runs-on: ubuntu-latest    # Map a step output to a job output
    outputs:
      # `should_skip` is output from `fkirc/skip-duplicate-actions@v5`
      is_duplicate: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with: 
          concurrent_skipping: 'same_content_newer'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  test:
    runs-on: ubuntu-latest
    needs: check_duplicate
    if: needs.check_duplicate.outputs.is_duplicate != 'true'
    steps:
      - run: echo hello

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() || failure() }}
    steps:
      - run: echo "suppose I'm notifying slack"
