name: Test (scratch)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo hello

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() || failure() }}
    steps:
      - run: echo "suppose I'm notifying slack"
